server:
  port: 8080
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test3?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      db-type: mysql
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml



